#:schema node_modules/wrangler/config-schema.json

name = "bolt"
compatibility_flags = ["nodejs_compat"]
compatibility_date = "2024-07-01"
pages_build_output_dir = "./build/client"

# 添加 build 配置
[build]
command = "npm install -g pnpm && pnpm install && pnpm run build"


# 确保添加项目的环境变量（如果有需要的话）
[env]
# 例如，如果您需要配置一些环境变量，可以在这里定义
